### ISSUE TITLE
 dcrseedhextowords.Linux.64-bit.zip contains MS Windows version

### ISSUE THREAD

**Issue by HamishMacEwan** [davecgh/dcrseedhextowords#1]
It might be nice if Decrediton accepted the hex seed, or at least a single paste of the words from the idiosyncratic list used.

**Comment by davecgh** [comment]
Thanks for the report.  I updated it with release v1.0.0 and corrected that issue.  I also change both Linux and Mac over to use `tar.gz` instead of `.zip` which is the typical format for those platforms.

https://github.com/davecgh/dcrseedhextowords/releases/tag/v1.0.0
